import { jsPDF } from 'jspdf';
import { PatientRow } from '@/types/database';

type RxDrug = {
  trade_name: string;
  generic_name: string;
  dose: string;
  frequency: string;
  duration: string;
  trade_name_ar?: string;
};

/**
 * Generate Prescription PDF matching Dr. Amgad's template
 * Based on Prescription PDF.pdf template
 */
export const generateRxPDF = (
  patient: PatientRow,
  drugs: RxDrug[],
  doctorName: string = "Dr. Amgad Khairy Kamel",
  diagnosis: string = ""
) => {
  const doc = new jsPDF();
  const pageWidth = 210; // A4 width in mm
  const margin = 20;

  // ========== HEADER ==========
  // Doctor Name - centered, large
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(doctorName, pageWidth / 2, 18, { align: 'center' });

  // Credentials
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text("M.B.B.Ch, M.Sc. Psychiatry", pageWidth / 2, 26, { align: 'center' });

  // Address
  doc.setFontSize(10);
  doc.text("250 Teraa Elbolakya St., Shoubra, Cairo", pageWidth / 2, 33, { align: 'center' });

  // Phone numbers
  doc.setTextColor(80, 80, 80);
  doc.text("Tel: 0100 100 6013 / 0122 326 1827", pageWidth / 2, 40, { align: 'center' });

  // Decorative line under header
  doc.setDrawColor(0, 100, 100);
  doc.setLineWidth(0.5);
  doc.line(margin, 45, pageWidth - margin, 45);

  // ========== PATIENT INFO ==========
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');

  // Date - right aligned
  const today = new Date();
  const dateStr = today.toLocaleDateString('en-GB', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric'
  });
  doc.text(`Date: ${dateStr}`, pageWidth - margin, 55, { align: 'right' });

  // Patient Name
  doc.setFont('helvetica', 'bold');
  doc.text("Patient Name:", margin, 55);
  doc.setFont('helvetica', 'normal');
  doc.text(patient.full_name, margin + 35, 55);

  // Patient Code and Age
  doc.text(`Code: ${patient.patient_code}`, margin, 63);
  doc.text(`Age: ${patient.age || 'N/A'} years`, margin + 50, 63);

  // ========== DIAGNOSIS ==========
  if (diagnosis) {
    doc.setFont('helvetica', 'bold');
    doc.text("Diagnosis:", margin, 73);
    doc.setFont('helvetica', 'normal');
    const diagnosisText = diagnosis.substring(0, 60); // Limit length
    doc.text(diagnosisText, margin + 28, 73);
  }

  // Line before Rx
  doc.setDrawColor(150, 150, 150);
  doc.setLineWidth(0.2);
  doc.line(margin, 80, pageWidth - margin, 80);

  // ========== Rx PRESCRIPTION AREA ==========
  // Rx symbol
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text("R/", margin, 92);

  // Prescription items with ruled lines
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');

  let currentY = 100;
  const lineHeight = 18;
  const leftCol = margin + 5;

  drugs.forEach((drug, index) => {
    // Drug number and name
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 80, 80);
    doc.text(`${index + 1}.`, leftCol, currentY);
    doc.text(drug.trade_name, leftCol + 8, currentY);

    // Generic name in parentheses
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(9);
    doc.text(`(${drug.generic_name})`, leftCol + 8 + doc.getTextWidth(drug.trade_name) + 3, currentY);

    // Dosage instruction line
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    const instruction = `${drug.dose} - ${formatFrequency(drug.frequency)} - ${drug.duration}`;
    doc.text(instruction, leftCol + 12, currentY + 7);

    // Ruled line under each drug
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.1);
    doc.line(leftCol, currentY + 12, pageWidth - margin, currentY + 12);

    currentY += lineHeight;

    // Check for page overflow
    if (currentY > 250) {
      doc.addPage();
      currentY = 30;
    }
  });

  // Empty ruled lines for writing
  const emptyLines = Math.max(3, 8 - drugs.length);
  for (let i = 0; i < emptyLines; i++) {
    doc.setDrawColor(220, 220, 220);
    doc.line(leftCol, currentY, pageWidth - margin, currentY);
    currentY += 8;
  }

  // ========== SIGNATURE AREA ==========
  // Signature line at bottom right
  const sigY = 270;
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.3);
  doc.line(pageWidth - 70, sigY, pageWidth - margin, sigY);
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text("Signature", pageWidth - margin - 25, sigY + 5);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Clinic-OS", pageWidth / 2, 287, { align: 'center' });

  // Save PDF
  const fileName = `Rx_${patient.patient_code}_${today.getTime()}.pdf`;
  doc.save(fileName);

  return fileName;
};

/**
 * Format frequency with readable text
 */
const formatFrequency = (frequency: string): string => {
  const frequencyMap: Record<string, string> = {
    'OD': 'Once daily',
    'BID': 'Twice daily',
    'TID': '3x daily',
    'QID': '4x daily',
    'QHS': 'At bedtime',
    'QOD': 'Every other day',
    'PRN': 'As needed',
    'AC': 'Before meals',
    'PC': 'After meals',
    'STAT': 'Immediately',
  };

  return frequencyMap[frequency.toUpperCase()] || frequency;
};
